### Python Libraries - Numpy, Matplotlib, OpenCV, Pandas

#### Numpy

Adds support for arrays, matrices and mathematical operations

In [3]:
import numpy as np

In [4]:
a = np.array([10,5,12,3,9])

In [5]:
print (a)

[10  5 12  3  9]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.shape)

(5,)


Shape gives the dimensions of the numpy array

In [11]:
two_d_array = np.array([[5,1,3,2],[6,3,2,9]])

In [12]:
print (two_d_array)

[[5 1 3 2]
 [6 3 2 9]]


In [13]:
print(two_d_array.shape)

(2, 4)


In [14]:
np.dot(two_d_array, two_d_array.T)

array([[ 39,  57],
       [ 57, 130]])

In [15]:
matrix = np.random.randint(10, 90, (3,4))

In [16]:
print (matrix)

[[39 25 36 41]
 [80 42 65 30]
 [42 61 87 75]]


In [17]:
print(matrix.T)

[[39 80 42]
 [25 42 61]
 [36 65 87]
 [41 30 75]]


In [19]:
np.max(matrix) #max of array

87

In [21]:
np.min(matrix)

25

In [23]:
a = np.array([3, 2, 0, -4, 8, 10])

In [24]:
np.argmin(a) #prints index of min. element

3

In [25]:
b = np.array([1,2,1,3,4,2,2,3,1,4])

In [27]:
print(np.unique(b, return_counts=True))

(array([1, 2, 3, 4]), array([3, 3, 2, 2]))


We get two arrays - one with the unique elements and the second with their complexities

In [28]:
matrix

array([[39, 25, 36, 41],
       [80, 42, 65, 30],
       [42, 61, 87, 75]])

In [31]:
matrix[1:3,2:4]

array([[65, 30],
       [87, 75]])